### PR TITLE
Format correctly DynamoDBJournalConfig toString

### PR DESCRIPTION
**Pull request by sergigp**
A parenthesis is missing. Big contribution, you are welcome :trollface:

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @sergigp,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by raboof — APPROVED** [review]
I think we need to notify the community and increase the major version number after merging this change.

**Review by johanandren — APPROVED** [review]

**Comment by rgomezcasas** [comment]
🤣 🤣 🤣

**Comment by ktoso** [comment]
LGTM ;)
Thanks :)

**Pull request merged**
