### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### akka/akka-persistence-dynamodb now has a Chat Room on Gitter

@ktoso has just created a chat room. You can visit it here: [https://gitter.im/akka/akka-persistence-dynamodb](https://gitter.im/akka/akka-persistence-dynamodb?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/akka/akka-persistence-dynamodb?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @gitter-badger,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by patriknw** [comment]
LGTM, but maybe you have to submit this in your name to pass CLA checker

**Comment by ktoso** [comment]
Thanks badger :wink: I'll steal the markdown from this PR :)

**Comment by rkuhn** [comment]
A gitter-badger is probably a close relative of the honey badger: it does not care.

**Comment by ktoso** [comment]
just doesn't care https://www.youtube.com/watch?v=4r7wHMg5Yjg

**Pull request closed without merging**
