### PR TITLE
Adding scalafmt #103

### PR DESCRIPTION
**Pull request by rmmeans**
Updating this project to use scalafmt #103

* The scalafmt conf file is taken *almost* exactly from [Akka](https://github.com/akka/akka/blob/main/.scalafmt.conf). 
* I know scalafmt preferences can vary, please let me know if any adjustments need to be made and I'll be happy to make them and update the PR.

I have some other work that I hope to contribute to this project soon, but first I wanted to see if there was any interest in getting scalafmt on the project first without any other changes.

### CODE REVIEW

**Comment by coreyoconnor** [comment]
Thanks! This is great :) Definitely appreciated.

I'll fix the travis CI. That should be disabled now that github CI is enabled.

**Review by coreyoconnor — APPROVED** [review]
LGTM. Once I fix the CI: update the PR and you should be OK to merge.

The typesafe CLA has been acting up. If you've already signed the CLA let me know and I'll ask akka people to override.

**Comment by rmmeans** [comment]
@coreyoconnor, yes I have previously signed the CLA.

**Comment by rmmeans** [comment]
@coreyoconnor I have a PR for discussion on #106, but due to scalafmt being applied to my local work, if we can merge this one first that would probably be useful.

**Comment by johanandren** [comment]
I have manually checked and can confirm that rmmeans has signed the CLA (sorry for issues with the validator recently)!

**Pull request merged**
