### PR TITLE
disable travis CI

### PR DESCRIPTION
**Pull request by coreyoconnor**
Disables Travis CI. A subsequent PR will add in the (now missing) release push.
This is to unblock merging the other PRs.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @coreyconnor,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by coreyoconnor** [comment]
@johanandren I intended to for this to include the change to the matrix names. However, those seem to be synthesized with no option for customization. With the base check name being "Build and Test". Do you have a reference for how these can be customized?

I'm basing much of the CI changes on:

* https://github.com/akka/akka-management/pull/889/files#diff-cd0effce06f425599e96952f4d5f684641a683f46d9909e7c74a9f8b2f03ccd3R21

**Comment by johanandren** [comment]
Not sure if I understood what the question correctly, but I don't know if/how you can change the top level workflow name (with all the matrix params added) but in the branch protection settings you could perhaps instead depend on the step name which already is a bit less specific and only contains Java and Scala versions.

**Comment by johanandren** [comment]
About the grumpy CLA checker here, it says `coreyconnor` not being in the CLA database, which it isn't, but your github handle is `coreyoconnor`, which is in the db, did you change the handle recently or something?

**Review by johanandren — APPROVED** [review]

**Comment by coreyoconnor** [comment]
Hi @johanandren 

My question is probably not clear. For "in the branch protection settings you could perhaps instead depend on..." I'm only guessing what the branch protection controls are: I don't have authorization for that page. So I'm not sure what the exact issue is or what should be changed. 

Likewise: I don't have the authorization to merge PRs that fail any checks. 

As for the question about the CLA handle: My handle has always been `coreyoconnor` - never been changed. That other handle is fascinating as there are no repos but they have a badge that references my repos O_o ( https://github.com/coreyconnor )

**Comment by coreyoconnor** [comment]
Didn't mean to cut the above short; got pulled away. Meant to summarize it down to explicit requests:

Can you (@johanandren ) point me to some one or a chat I can ask about getting the branch protections fixed? I can't do this myself with my current authorizations. :/

Similarly: I still need to update the CI to do releases (AFAICT anyways). Which I'd definitely need help with. There looks to be typesafe secrets required for release pushes to sonatype. Do you know where would be best to ask about this?

Thanks for your help! :)

**Comment by johanandren** [comment]
I just gave you maintainer access, check if that is enough, if not let me know what you want for the required checks in branch protection and I can fix that.

For releases that's a little bit more work but I should be able to help out with automating that as well, but can't do that immediately, perhaps the coming weeks, would that be ok?

**Comment by johanandren** [comment]
For the username/CLA the problem is that there is something wrong in your local git setup, so the actual commits says `coreyconnor` was the author. In addition to fixing default/global config you should be able to fix the existing commit here through `git commit --amend --author="correct author"` and force push this branch.

**Comment by coreyoconnor** [comment]
> I just gave you maintainer access, check if that is enough, if not let me know what you want for the required checks in branch protection and I can fix that.
> 
> For releases that's a little bit more work but I should be able to help out with automating that as well, but can't do that immediately, perhaps the coming weeks, would that be ok?

Thanks! I'll see how far I can get with maintainer access.

In the coming weeks will be fine. I'll be merging the other PRs and doing a bit more for the next release. At my pace that's definitely a few weeks ;)

Thanks again for the assistance.

**Comment by coreyoconnor** [comment]
> For the username/CLA the problem is that there is something wrong in your local git setup, so the actual commits says `coreyconnor` was the author. In addition to fixing default/global config you should be able to fix the existing commit here through `git commit --amend --author="correct author"` and force push this branch.

that's... a really silly error on my part haha. I will get that updated appropriately.

**Pull request merged**
